apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: gitops-demo
  name: gitops-demo
  namespace: dev
spec: 
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 31000
  selector:
    app: gitops-demo
    version: v1
