apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: gitops-demo
  name: gitops-demo
  namespace: dev
spec: 
  type: NodePort
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 80
    nodePort: 31000
  selector:
    app: gitops-demo
